let b1f1 = document.querySelector('.building1floor1');
let b1f2 = document.querySelector('.building1floor2');
let b1f3 = document.querySelector('.building1floor3');
let b1f4 = document.querySelector('.building1floor4');
let b2f1 = document.querySelector('.building2floor1');
let b2f2 = document.querySelector('.building2floor2');
let b2f3 = document.querySelector('.building2floor3');
let b2f4 = document.querySelector('.building2floor4');
let b2f5 = document.querySelector('.building2floor5');
let b2f6 = document.querySelector('.building2floor6');

b1f1.style.display = 'none';
b1f3.style.display = 'none';
b1f4.style.display = 'none';
b2f1.style.display = 'none';
b2f2.style.display = 'none';
b2f3.style.display = 'none';
b2f4.style.display = 'none';
b2f5.style.display = 'none';
b2f6.style.display = 'none';

let b1f1list = document.querySelector('.b1floor1');
let b1f2list = document.querySelector('.b1floor2');
let b1f3list = document.querySelector('.b1floor3');
let b1f4list = document.querySelector('.b1floor4');
let b2f1list = document.querySelector('.b2floor1');
let b2f2list = document.querySelector('.b2floor2');
let b2f3list = document.querySelector('.b2floor3');
let b2f4list = document.querySelector('.b2floor4');
let b2f5list = document.querySelector('.b2floor5');
let b2f6list = document.querySelector('.b2floor6');

b1f1list.onclick = function() {
    b1f1.style.display = 'block';
    b1f2.style.display = 'none';
    b1f3.style.display = 'none';
    b1f4.style.display = 'none';
    b2f1.style.display = 'none';
    b2f2.style.display = 'none';
    b2f3.style.display = 'none';
    b2f4.style.display = 'none';
    b2f5.style.display = 'none';
    b2f6.style.display = 'none';
}
b1f2list.onclick = function() {
    b1f1.style.display = 'none';
    b1f2.style.display = 'block';
    b1f3.style.display = 'none';
    b1f4.style.display = 'none';
    b2f1.style.display = 'none';
    b2f2.style.display = 'none';
    b2f3.style.display = 'none';
    b2f4.style.display = 'none';
    b2f5.style.display = 'none';
    b2f6.style.display = 'none';
}
b1f3list.onclick = function() {
    b1f1.style.display = 'none';
    b1f2.style.display = 'none';
    b1f3.style.display = 'block';
    b1f4.style.display = 'none';
    b2f1.style.display = 'none';
    b2f2.style.display = 'none';
    b2f3.style.display = 'none';
    b2f4.style.display = 'none';
    b2f5.style.display = 'none';
    b2f6.style.display = 'none';
}
b1f4list.onclick = function() {
    b1f1.style.display = 'none';
    b1f2.style.display = 'none';
    b1f3.style.display = 'none';
    b1f4.style.display = 'block';
    b2f1.style.display = 'none';
    b2f2.style.display = 'none';
    b2f3.style.display = 'none';
    b2f4.style.display = 'none';
    b2f5.style.display = 'none';
    b2f6.style.display = 'none';
}
b2f1list.onclick = function() {
    b1f1.style.display = 'none';
    b1f2.style.display = 'none';
    b1f3.style.display = 'none';
    b1f4.style.display = 'none';
    b2f1.style.display = 'block';
    b2f2.style.display = 'none';
    b2f3.style.display = 'none';
    b2f4.style.display = 'none';
    b2f5.style.display = 'none';
    b2f6.style.display = 'none';
}
b2f2list.onclick = function() {
    b1f1.style.display = 'none';
    b1f2.style.display = 'none';
    b1f3.style.display = 'none';
    b1f4.style.display = 'none';
    b2f1.style.display = 'none';
    b2f2.style.display = 'block';
    b2f3.style.display = 'none';
    b2f4.style.display = 'none';
    b2f5.style.display = 'none';
    b2f6.style.display = 'none';
}
b2f3list.onclick = function() {
    b1f1.style.display = 'none';
    b1f2.style.display = 'none';
    b1f3.style.display = 'none';
    b1f4.style.display = 'none';
    b2f1.style.display = 'none';
    b2f2.style.display = 'none';
    b2f3.style.display = 'block';
    b2f4.style.display = 'none';
    b2f5.style.display = 'none';
    b2f6.style.display = 'none';
}
b2f4list.onclick = function() {
    b1f1.style.display = 'none';
    b1f2.style.display = 'none';
    b1f3.style.display = 'none';
    b1f4.style.display = 'none';
    b2f1.style.display = 'none';
    b2f2.style.display = 'none';
    b2f3.style.display = 'none';
    b2f4.style.display = 'block';
    b2f5.style.display = 'none';
    b2f6.style.display = 'none';
}
b2f5list.onclick = function() {
    b1f1.style.display = 'none';
    b1f2.style.display = 'none';
    b1f3.style.display = 'none';
    b1f4.style.display = 'none';
    b2f1.style.display = 'none';
    b2f2.style.display = 'none';
    b2f3.style.display = 'none';
    b2f4.style.display = 'none';
    b2f5.style.display = 'block';
    b2f6.style.display = 'none';
}
b2f6list.onclick = function() {
    b1f1.style.display = 'none';
    b1f2.style.display = 'none';
    b1f3.style.display = 'none';
    b1f4.style.display = 'none';
    b2f1.style.display = 'none';
    b2f2.style.display = 'none';
    b2f3.style.display = 'none';
    b2f4.style.display = 'none';
    b2f5.style.display = 'none';
    b2f6.style.display = 'block';
}